from database.database import get_connection, create_ventas_calzado_table, create_ventas_medias_table, check_table_exists, create_tables_if_not_exists,clean_database_calzados, clean_database_medias


